apiVersion: apps/v1
kind: Deployment
metadata:
  name: design91-kafka
  namespace: design91-infrastructure
  labels:
    app: design91-kafka
    component: streaming
    project: design91
spec:
  replicas: 1
  strategy:
    type: Recreate  # Prevents concurrent pods accessing same PVC
  selector:
    matchLabels:
      app: design91-kafka
  template:
    metadata:
      labels:
        app: design91-kafka
        component: streaming
        project: design91
    spec:
      terminationGracePeriodSeconds: 120  # Allow graceful Kafka shutdown
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.4.0
        ports:
        - containerPort: 29092
          name: internal
        - containerPort: 9092
          name: external
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "design91-zookeeper:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://design91-kafka:29092,PLAINTEXT_HOST://localhost:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "168"
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        livenessProbe:
          exec:
            command:
            - kafka-broker-api-versions
            - --bootstrap-server
            - localhost:9092
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "kafka-server-stop.sh"]
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: design91-kafka-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: design91-kafka
  namespace: design91-infrastructure
  labels:
    app: design91-kafka
    component: streaming
    project: design91
    port-forward: "enabled"
  annotations:
    port-forward.design91.io/ports: "9092"
    port-forward.design91.io/description: "Kafka broker external access"
spec:
  type: ClusterIP
  ports:
  - name: kafka-internal
    port: 29092
    targetPort: 29092
    protocol: TCP
  - name: kafka-external
    port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: design91-kafka
