apiVersion: apps/v1
kind: Deployment
metadata:
  name: design91-zookeeper
  namespace: design91-infrastructure
  labels:
    app: design91-zookeeper
    component: coordination
    project: design91
spec:
  replicas: 1
  selector:
    matchLabels:
      app: design91-zookeeper
  template:
    metadata:
      labels:
        app: design91-zookeeper
        component: coordination
        project: design91
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.4.0
        ports:
        - containerPort: 2181
          name: client
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        volumeMounts:
        - name: zookeeper-data
          mountPath: /var/lib/zookeeper/data
        - name: zookeeper-logs
          mountPath: /var/lib/zookeeper/log
        livenessProbe:
          tcpSocket:
            port: 2181
          initialDelaySeconds: 40
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 2181
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: zookeeper-data
        persistentVolumeClaim:
          claimName: design91-zookeeper-data-pvc
      - name: zookeeper-logs
        persistentVolumeClaim:
          claimName: design91-zookeeper-logs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: design91-zookeeper
  namespace: design91-infrastructure
  labels:
    app: design91-zookeeper
    component: coordination
    project: design91
    port-forward: "internal-only"
  annotations:
    port-forward.design91.io/description: "Zookeeper - internal Kafka coordination only"
spec:
  type: ClusterIP
  ports:
  - port: 2181
    targetPort: 2181
    name: client
  selector:
    app: design91-zookeeper
