apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: design91-plugin-manager-hpa
  namespace: design91-infrastructure
  labels:
    app: design91-plugin-manager
    component: autoscaling
    project: design91
    manager-type: plugin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: design91-plugin-manager
  
  # Scaling Configuration
  minReplicas: 1
  maxReplicas: 10
  
  # Scaling Metrics
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  # Custom metrics (if available)
  # - type: Pods
  #   pods:
  #     metric:
  #       name: http_requests_per_second
  #     target:
  #       type: AverageValue
  #       averageValue: "100"
  
  # Scaling Behavior
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
