apiVersion: v1
kind: ConfigMap
metadata:
  name: design91-hazelcast-config
  namespace: design91-infrastructure
  labels:
    project: design91
    component: cache
    service: hazelcast
data:
  hazelcast.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xmlns="http://www.hazelcast.com/schema/config"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.hazelcast.com/schema/config
               http://www.hazelcast.com/schema/config/hazelcast-config-5.3.xsd">

        <cluster-name>EntitiesManager</cluster-name>

        <network>
            <port auto-increment="true" port-count="100">5701</port>
            <outbound-ports>
                <ports>0</ports>
            </outbound-ports>
            <join>
                <multicast enabled="false"/>
                <tcp-ip enabled="true">
                    <interface>0.0.0.0</interface>
                    <member-list>
                        <member>design91-hazelcast</member>
                    </member-list>
                </tcp-ip>
            </join>
        </network>

        <map name="processor-health">
            <time-to-live-seconds>300</time-to-live-seconds>
            <max-idle-seconds>60</max-idle-seconds>
        </map>

        <map name="processor-activity">
            <time-to-live-seconds>3600</time-to-live-seconds>
            <max-idle-seconds>300</max-idle-seconds>
        </map>

        <map name="orchestration-data">
            <time-to-live-seconds>0</time-to-live-seconds>
            <max-idle-seconds>0</max-idle-seconds>
        </map>

        <management-center scripting-enabled="true"/>

    </hazelcast>
