apiVersion: apps/v1
kind: Deployment
metadata:
  name: design91-elasticsearch
  namespace: design91-infrastructure
  labels:
    app: design91-elasticsearch
    component: search
    project: design91
spec:
  replicas: 1
  strategy:
    type: Recreate  # Prevents concurrent pods accessing same PVC
  selector:
    matchLabels:
      app: design91-elasticsearch
  template:
    metadata:
      labels:
        app: design91-elasticsearch
        component: search
        project: design91
    spec:
      terminationGracePeriodSeconds: 120  # Allow graceful Elasticsearch shutdown
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.security.enrollment.enabled
          value: "false"
        - name: xpack.security.http.ssl.enabled
          value: "false"
        - name: xpack.security.transport.ssl.enabled
          value: "false"
        - name: cluster.name
          value: "design91-cluster"
        - name: node.name
          value: "design91-node"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: http.cors.enabled
          value: "true"
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "curl -X POST 'localhost:9200/_cluster/nodes/_local/_shutdown'"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: design91-elasticsearch-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: design91-elasticsearch
  namespace: design91-infrastructure
  labels:
    app: design91-elasticsearch
    component: search
    project: design91
    port-forward: "enabled"
  annotations:
    port-forward.design91.io/ports: "9200"
    port-forward.design91.io/description: "Elasticsearch search and analytics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: 9300
    targetPort: 9300
    protocol: TCP
  selector:
    app: design91-elasticsearch
