apiVersion: v1
kind: ConfigMap
metadata:
  name: design91-otel-collector-config
  namespace: design91-infrastructure
  labels:
    project: design91
    component: telemetry
    service: otel-collector
data:
  otel-collector-config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:8081

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets: ['0.0.0.0:8888']

    processors:
      batch:
      attributes:
        actions:
          - key: http.status_code
            action: convert
            converted_type: int
          - key: StatusCode
            action: convert
            converted_type: int

    exporters:
      debug:
        verbosity: detailed
      elasticsearch:
        endpoints: ["http://design91-elasticsearch:9200"]
        logs_index: "design91-logs"
        traces_index: "design91-traces"
        mapping:
          mode: "ecs"
          dedot: false
      prometheus:
        endpoint: "0.0.0.0:8889"

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [attributes, batch]
          exporters: [debug, elasticsearch]
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [debug, prometheus]
        logs:
          receivers: [otlp]
          processors: [attributes, batch]
          exporters: [debug, elasticsearch]